version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y maven
  build:
    commands:
      - echo Packaging Jar file
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/app.jar
  discard-paths: yes